### ISSUE TITLE
How do I patch kubernetes with ansible-playbook

### ISSUE THREAD

**Issue by mhabicht** [IBM/ansible-kubernetes-ha-cluster#6]
I have a cluster that I have used ansible-playbook to configure. All works well but I am not able to "kubeadm upgrade" to install the latest security patch.

I though that if I changed the version in the hosts.ini it will install the latest version, but I get an error FAILED! => {"msg": "'dict object' has no attribute u'v1.11.5'"}

I see that adding "kubeadm upgrade"is in the works, but is there a current way to upgrade/patch my entire cluster from 1.11.3 to 1.11.5 using ansible-playbook? If not how can I patch?

**Comment by jeesmon** [comment]
@mhabicht Did you look at the `kubeadm-upgrade.yaml` playbook? Looks like it has the all the steps needed for upgrade (kubeadm upgrade apply and kubelet update).

**Comment by mhabicht** [comment]
https://github.com/IBM/ansible-kubernetes-ha-cluster

This was marked as such, has this been added?

"Work in progress:
We will add the following items to this repository:

Kubeadm upgrade playbook
Adding the possibility of using other user then root
Addons, Prometheus support?"

However I believe I received the answer here. Have not been able to test yet.
https://github.com/kubernetes-sigs/kubespray/issues/3819#issuecomment-444549770

**Comment by mhabicht** [comment]
Test and this did work.
kubernetes-sigs/kubespray#3819 (comment)
